### ISSUE TITLE
Error in match.names(clabs, names(xi)) :    names do not match previous names

### ISSUE THREAD

**Issue by gisynw** [JeremyGelb/spNetwork#10]
Hello, I had an issue with nkde function, I have tried to find information about this issue but failed. Thank you in advance for any help.

**Comment by gisynw** [comment]
Error in match.names(clabs, names(xi)) : 
  names do not match previous names
This is the error message that I got in R, thanks! please let me know if you need any other further information.

**Comment by JeremyGelb** [comment]
Hello ! I will check it as soon as possible, but I need to know the version of spNetwork you are using. I also need the data and code you are using (a small sample would be enough if it allows to reproduce the bug)

**Comment by gisynw** [comment]
Hello, thank yo uso much for your reply. spNetwork package version: 0.4.3.2. 
Attahced please find code and data. 
Thank you in advance for any help.
[spNetwork.zip](https://github.com/JeremyGelb/spNetwork/files/9462681/spNetwork.zip)

**Comment by JeremyGelb** [comment]
Hello !

This was not a major bug. The error message is raised because some of the columns in the dataset  `event` are creating conflicts with temporary columns I am using inside the function. You could just remove the following columns : 

```
event$X_1 <- NULL
event$X <- NULL
event$ID <- NULL
```

And it will work !

You should also check your data with Qgis. You have three points far away of the rest of your network.
![image](https://user-images.githubusercontent.com/46856737/188246797-ad8fc3dd-6e3f-46f7-a6b5-09accc0a46de.png)

Let me know if you want me to delete this image.

I will add a warning about this problem in the next version of the package.

Let me know if the problem is solved on your side.

**Comment by gisynw** [comment]
Hello！

Thank you so much for helping me solve this! 
It's ok to leave this image on. I will cite your reference if we publish any paper on it. 

Thanks, have a good day

**Comment by JeremyGelb** [comment]
My pleasure! And it would be very kind of you to cite either the package spNetwork or the article published in the R journal.
