### ISSUE TITLE
Package Installation Error

### ISSUE THREAD

**Issue by rezashami** [JeremyGelb/spNetwork#24]
Hi,
I have a problem with package installation. When I run the `install.packages("spNetwork")` code in the R Interactive terminal in VS Code, I face this error message:

 ```
package 'spNetwork' is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
```

My R version is 4.4.1 (2024-06-14 ucrt).

How can I fix this problem and install the package?
Thanks.

**Comment by JeremyGelb** [comment]
Hello !

SpNetwork has been removed from CRAN for a week because an example raised an error dur to a new type of test imposed by CRAN (UBSAN testing on c++). It took me a while to be able to reproduce the bug. It has been corrected and is now back on CRAN. If it happens again, you can still install spNetwork from github with the command : 

devtools::install_github("JeremyGelb/spNetwork")
